### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by sucof** [GeekGhc/zhihu-app#1]
比laravist视频内容多做了很多工作啊，不过作为一个知识问答app，可能需要一些标签，让回答者不要看内容也知道自己对该问题的大概了解程度，例如知乎的圆桌，在一些主题标签下再提问，让网站更易使用；同时，用户也可以做一些区别，例如是机构用户还是普通用户，是大拿还是其它什么，一点建议。

**Comment by GeekGhc** [comment]
好的 后面有机会我再改进下 非常感谢你的建议

**Comment by Jimmy9876** [comment]
好像有些bug

**Comment by GeekGhc** [comment]
@Jimmy9876   有的部分已修复
