### ISSUE TITLE
初始化项目时sql报错

### ISSUE THREAD

**Issue by WKlili** [GeekGhc/zhihu-app#10]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; ch  
  eck the manual that corresponds to your MySQL server version for the right syntax to use near 'j  
  son null, `remember_token` varchar(100) null, `created_at` timestamp null, `upd' at line 1 

建立user表的时候报错了，我不知道你依赖的mysql版本是多少==还是说确实有问题呢。我用的mysql版本是5.6的

**Comment by WKlili** [comment]
解决啦，确实是mysql版本的原因--希望可以注释一下，项目环境，像我这种小白其实还是蛮困惑的--

**Comment by WKlili** [comment]
还有package.json里依赖的库也没有写全--。。。。比如 "buble": "^0.19.3","buble-loader": "^0.2.2"都是有依赖版本的--高版本不兼容项目里的版本了。。

**Comment by ghost** [comment]
mysql 需要哪个版本？
