### ISSUE TITLE
打扰一下，登录之后，写好问题后报错了，错误提示如下面内容：

### ISSUE THREAD

**Issue by wszwj** [GeekGhc/zhihu-app#2]
Type error: Argument 1 passed to App\Repositories\QuestionRepository::normalizeTopics() must be of the type array, null given, called in E:\phpStudy\WWW\zhihu-app\app\Http\Controllers\QuestionsController.php on line 41

**Comment by GeekGhc** [comment]
这是因为Topics不是数组类型或者值为空  我这边是没问题的  你可以看一下创建时的topics是不是数组数据 可以看下传递过来的topics数据

**Comment by Jimmy9876** [comment]
请问在哪里关闭邮箱验证

**Comment by GeekGhc** [comment]
@Jimmy9876   你需要在关闭哪里的邮箱 在控制器方法里注释掉相应的事件就行了

**Comment by Jimmy9876** [comment]
第二次登陆密码错误或者邮箱未验证怎么解决
