### ISSUE TITLE
php artisan zhihu:install   

### ISSUE THREAD

**Issue by IcahnBryan** [GeekGhc/zhihu-app#4]
PHP Warning:  require(/home/ubuntu/Projects/zhihu-app/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /home/ubuntu/Projects/zhihu-app/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/home/ubuntu/Projects/zhihu-app/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/ubuntu/Projects/zhihu-app/bootstrap/autoload.php on line 17

**Comment by Yudingding** [comment]
This is Issues of competence.
In the way:
1. cd /home/ubuntu/Projects
2. chmod 775 zhihu-app -R
