### ISSUE TITLE
页面的样式无效

### ISSUE THREAD

**Issue by Stepkim** [GeekGhc/zhihu-app#8]
创建管理员之后访问，页面的样式无效
![zhihu-app](https://user-images.githubusercontent.com/14869623/39282613-a6f5eeb4-493c-11e8-97bb-6afe954049be.png)

**Comment by GeekGhc** [comment]
看下资源路径引用

**Comment by Stepkim** [comment]
![elixir](https://user-images.githubusercontent.com/14869623/39302203-69d6ca24-4984-11e8-8edb-aa82333a037a.png)
![app css](https://user-images.githubusercontent.com/14869623/39302204-6a5c2296-4984-11e8-9946-bf17d5d4c974.png)
尝试过使用gulp命令，然后会报错
![gulp](https://user-images.githubusercontent.com/14869623/39302506-7339a2ac-4985-11e8-94b2-53143329273c.png)
![gulp 1](https://user-images.githubusercontent.com/14869623/39302507-738cb96a-4985-11e8-970a-71697d6faf35.png)
![gulp 3](https://user-images.githubusercontent.com/14869623/39302505-72e711ae-4985-11e8-9dff-71aea5362172.png)

**Comment by GeekGhc** [comment]
删除下node_modules再npm下吧
