### ISSUE TITLE
无法编辑带有代码的问题描述

### ISSUE THREAD

**Issue by aunhappy** [GeekGhc/zhihu-app#9]
### 问题描述
添加问题的时候，如果描述中包含代码，添加成功后，再对问题进行编辑，页面显示空白，控制台console有报错

### 复现步骤
1. 添加一个问题，并在描述中粘贴从PHPstorm中复制的代码，发布问题
![image](https://user-images.githubusercontent.com/15842120/39404486-bced49ce-4bc6-11e8-993c-b6b40c1d4830.png)
2.点击编辑，编辑页面空白
![image](https://user-images.githubusercontent.com/15842120/39404503-f55f37e0-4bc6-11e8-88ad-747fe7145677.png)
3.控制台console有报错
```
Uncaught TypeError: Cannot read property 'offsetWidth' of null
    at UE.Editor.renderUI (ueditor.all.js:29264)
    at UE.Editor.fireEvent (ueditor.all.js:1619)
    at langReadied (ueditor.all.js:6566)
    at ueditor.all.js:6748
    at HTMLScriptElement.element.onload.element.onreadystatechange (ueditor.all.js:921)
renderUI @ ueditor.all.js:29264
fireEvent @ ueditor.all.js:1619
langReadied @ ueditor.all.js:6566
(anonymous) @ ueditor.all.js:6748
element.onload.element.onreadystatechange @ ueditor.all.js:921
```
4.在后台编辑问题正常

### 预期行为
在前台可以正常编辑

### 实际情况
无法编辑，编辑页空白

### 版本分支
master

**Comment by GeekGhc** [comment]
感谢反馈 我这边试了下是没问题的  控制台的报错是编辑器初始化内容高度问题

**Comment by aunhappy** [comment]
我应该是没动前端代码，现在应该怎么改呢？ @GeekGhc

**Comment by JamesHaii** [comment]
执行php artisan zhihu:install 报错是什么原因

**Comment by JamesHaii** [comment]
![@ W96US6H}`}KJ3F$55MK~6](https://user-images.githubusercontent.com/20207002/68572290-09910980-04a0-11ea-8199-bf83c1d7f1bb.jpg)

**Comment by JamesHaii** [comment]
这是什么问题，大神给解释一下，谢谢

**Comment by aunhappy** [comment]
No reply for too long, I choose to close this issue
